### ISSUE TITLE
Can't see annotations

### ISSUE THREAD

**Issue by TheRealXenquility** [Seirade/YouTube-Annotation-Player#2]
Hey there! I've gotten everything set up with youtube-dl and all that, and I can get the video playing via the php script. But, I can't actually see any of the annotations. I may be missing something here, but I've done everything I can think of.

**Comment by Seirade** [comment]
Do you have Javascript enabled?

**Comment by TheRealXenquility** [comment]
Indeed I do

**Comment by Seirade** [comment]
That's strange. Do you have a proper annotation XML file? If you downloaded any after January 15, 2019, it will just be blank. You'll need to grab an archived version.

Just so I can try on my end: which browser and version are you using, and which video are you testing with?

**Comment by TheRealXenquility** [comment]
When you mean downloading an archived version, does that just entail using the --datebefore command? Because if so, I am. Otherwise, my bad.

I'm using the latest version of firefox, with the most recent version of your program and youtube-dl, and I'm testing it with this video: https://www.youtube.com/watch?v=KFsv8tGHkHY

**Comment by Seirade** [comment]
Sorry if I didn't make that clear. The readme is also a little outdated now that archiving efforts are over. What I mean by archived version is the XML itself. You should have a file named "KFsv8tGHkHY.annotations.xml" in the folder along with the video. If you downloaded that file after January 15, 2019, it will be mostly blank and have no annotations. You would need an older (archived) version with all of the data still in it.

I looked around a few places, but I can't seem to find anyone who has a copy. Just to be sure yours isn't blank, could you please attach your XML file?

**Comment by TheRealXenquility** [comment]
Ah okay. Just checked, and yeah, the folder's blank. Thank you very much for the help!

**Comment by Seirade** [comment]
No problem! Before this issue is closed completely, I asked [omarroth](https://github.com/omarroth) if he had a copy, since his archive is much bigger (1.4 billion annotations), and sure enough, he had it! Could you test out with this version of the XML and confirm that it works? I tested on mine and it does, but I just want to make sure you have no other problems getting them to work.


[KFsv8tGHkHY.annotations.zip](https://github.com/Seirade/YouTube-Annotation-Player/files/2783987/KFsv8tGHkHY.annotations.zip)

**Comment by TheRealXenquility** [comment]
Awwww Sweet! I never thought I'd be able to see annotations again! Thank you so much for the help. Just had to make sure the annotations file was named the same as the video, and it worked like a charm!

**Comment by Seirade** [comment]
I'm glad it works! As of the time of writing this, a bunch of people with various scattered efforts have archived tons of metadata. Right now, we're working on getting them up somewhere such as [archive.org](https://archive.org/) and providing a way to make them accessible, via an API. If you're looking for a specific video's annotations, I'd keep my eyes peeled on that for the next month, as it's likely one of us has it.
